[package]
name = "rv32i"
version = "0.1.0"
authors = ["wakuto <waku.902002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
